[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR-BACKEND-HOST/:splat"
  status = 200
  force = true

# This ensures React Router works on Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
